<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard - SB Admin</title>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->appendStylesheet($this->basePath() . '/css/sb-admin.css')
                        ->appendStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
                        ?>
        
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
  </head>

  <body>

    <div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Admin Area - Movies App - ZF2 scaffold</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li <?php if ($this->layout()->controller=='dashboard') { ?>class="active"<?php } ?>>
                <a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a>
            </li>
            <li <?php if ($this->layout()->controller=='category') { ?>class="active"<?php } ?>>
                <a href="<?php echo $this->url('admin', array('controller'=>'category') ) ?>"><i class="fa fa-folder-open"></i> <?php echo $this->translate('Categories') ?></a>
            </li>
            <li <?php if ($this->layout()->controller=='movie') { ?>class="active"<?php } ?>>
                <a href="<?php echo $this->url('admin', array('controller'=>'movie') ) ?>"><i class="fa fa-youtube-play"></i> <?php echo $this->translate('Movies') ?></a>
            </li>
            <li <?php if ($this->layout()->controller=='admins') { ?>class="active"<?php } ?>>
                <a href="<?php echo $this->url('admin', array('controller'=>'admins') ) ?>"><i class="fa fa-users"></i> <?php echo $this->translate('Admin Users') ?></a>
            </li>
            <li <?php if ($this->layout()->controller=='settings') { ?>class="active"<?php } ?>>
                <a href="<?php echo $this->url('admin', array('controller'=>'settings') ) ?>"><i class="fa fa-wrench"></i> <?php echo $this->translate('Settings') ?></a>
            </li>
          </ul>


        <?php
        $loginBarData = array( 'username' => $this->layout()->loggedinUser );
        echo $this->partial('admin/auth/loginbarPartial.phtml', $loginBarData );
        ?>
        
        </div><!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">

        <?php echo $this->content; ?>

      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

    <!-- JavaScript -->
<?php
  echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery-1.10.2.js')
    ->prependFile($this->basePath() . '/js/bootstrap.js')
    ;
?>

    <!-- Page Specific Plugins -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
    
<?php
  echo $this->headScript()
    ->prependFile($this->basePath() . '/js/morris/chart-data-morris.js')
    ->prependFile($this->basePath() . '/js/tablesorter/jquery.tablesorter.js')
    ->prependFile($this->basePath() . '/js/tablesorter/tables.js')
    ;
?>

  </body>
</html>
