
<div class="row">
  <div class="col-lg-12">
    <h1>Movies <small>list</small></h1>
    
    <ol class="breadcrumb">
      <li><a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li class="active"><i class="fa fa-table"></i> Tables</li>
    </ol>
    <div class="alert alert-info alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      We're using <a class="alert-link" href="http://tablesorter.com/docs/">Tablesorter 2.0</a> for the sort function on the tables. Read the documentation for more customization options or feel free to use something else!
    </div>
  </div>
</div><!-- /.row -->

        
<div class="table-responsive">
 <table class="table table-bordered table-hover table-striped tablesorter">
   <thead>
     <tr>
       <th>Title <i class="fa fa-sort"></i></th>
       <th style="width:60px" >
        <a href="<?php echo $this->url('admin_movie', array('action'=>'addupdate'));?>" ><i class="fa fa-plus-circle"></i> add</a>
       </th>
     </tr>
   </thead>
   <tbody>
 <?php foreach ($res as $item) : ?>
 <tr>
     <td>
        <?php echo $this->escapeHtml($item['title']);?>
    </td>
     <td>
        <a href="<?php echo $this->url('admin_movie', array('action'=>'addupdate', 'id' => $item['id'])) ?>"><i class="fa fa-edit"></i></a>
        -
        <a href="<?php echo $this->url('admin_movie', array('action'=>'delete', 'id' => $item['id'])) ?>"><i class="fa fa-minus-circle"></i></a>
    </td>
 </tr>
 <?php endforeach ?>
   </tbody>
 </table>
</div>
