<?php

 $title = $cur_cat.' Movies';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 *<?php var_dump($this->identity()); ?>*
 <table class="table">
 <?php foreach ($res as $item) : ?>
 <tr>
     <td>
        <a href="<?php echo $this->url('movie', array('action'=>'edit', 'id' => $item['id']));?>" >
            <?php echo $this->escapeHtml($item['title']);?>
        </a>
    </td>
 </tr>
 <?php endforeach; ?>
 </table>