<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ?>

    </head>
    <body>
        <div class="container">
                <?php echo $this->content; ?>
        </div> <!-- /container -->

        <hr>
        <footer>
            <p>&copy; <?php echo date('Y') ?> by Colceriu Ovidiu. <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
    </body>
</html>
